### ISSUE TITLE
Scraper fails when profile is unavailable

### ISSUE THREAD

**Issue by domus71** [leonardiwagner/scrapedin#163]

**Comment by domus71** [comment]
From LinkedIn, I receive that the current profile is not available and scraper fails with the following error:

TypeError: Cannot read property 'name' of undefined
    at module.exports (D:\nodejs\XXXXX\node_modules\scrapedin\src\profile\cleanProfileData.js:5:23)
    at module.exports (D:\nodejs\XXXXX\node_modules\scrapedin\src\profile\profile.js:79:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
