### ISSUE TITLE
Error: LinkedIn website changed and scrapedin 1.0.21 can't read basic data.

### ISSUE THREAD

**Issue by ghost** [leonardiwagner/scrapedin#164]
Hello,

Getting this error message. Reporting as suggested.

scrapedin: 2021-08-17T16:23:12.621Z error: [profile/cleanProfileData.js] LinkedIn website changed and scrapedin 1.0.21 can't read basic data. Please report this issue at https://github.com/linkedtales/scrapedin/issues
Error: LinkedIn website changed and scrapedin 1.0.21 can't read basic data. Please report this issue at https://github.com/linkedtales/scrapedin/issues
    at module.exports (/home/cgd/scratch/linkedin/node_modules/scrapedin/src/profile/cleanProfileData.js:8:11)
    at module.exports (/home/cgd/scratch/linkedin/node_modules/scrapedin/src/profile/profile.js:79:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async pull_async (/home/cgd/scratch/linkedin/run.js:20:29)
    at async Task.cron.schedule.scheduled [as _execution] (/home/cgd/scratch/linkedin/run.js:33:17)

**Comment by ghost** [comment]
I see that there is a fix, apologies for duplicating issue. Please could this be put in updated release!

https://github.com/linkedtales/scrapedin/blob/642668e8b0f04ec3f2d8d62753d1aaf9e0340339/src/profile/profileScraperTemplate.js
